apiVersion: v1
kind: Secret
metadata:
  name: godemode-backend-secrets
  namespace: godemode
type: Opaque
stringData:
  # Anthropic Claude API Key
  # Get your key from: https://console.anthropic.com/
  ANTHROPIC_API_KEY: "your-api-key-here"

  # Optional: Database connection string if needed
  # DATABASE_URL: "postgresql://user:password@host:port/dbname"

  # Optional: Additional secrets
  # JWT_SECRET: "your-jwt-secret"
  # API_ENCRYPTION_KEY: "your-encryption-key"
